### ISSUE TITLE
how to deal with NA in memory correction

### ISSUE THREAD

**Issue by twollnik** [EarthSystemDiagnostics/piccr#22]
@thomas-muench 
The picarro measurement data can contain NA values, e.g.:

Line | Inj Nr | Identifier1 | d(18_16)Mean | ...
--- | --- |--- |--- | ---
51 | 1 | A | 1
52 | 2 | A |1
53 | 3 | A | 1
54 | 1 | B | NA
55 | 2 | B | NA
56 | 3 | B | NA
57 | 1 | C | 2
58 | 2 | C | 2
59 | 3 | C | 2

We don't have access to a true value for B when calcuating the memory corrected values for C. How should the memory corrected values for C be calculated?

**Comment by thomas-muench** [comment]
This is indeed a major problem. If only single injections for one sample are NA, then memory coefficients and the approximated true value for the previous sample can be still calculated using `na.rm = TRUE` - as already done. But when all injections for this sample are NA, as you illustrate, there is no way of calculating the true value for this sample.

I guess the question is then why and how the measurement of this sample failed: 

If, for any reason, no water was injected at all into the device cavity for this sample, then one could argue that the true previous value should be obtained from the last successfull sample before, since water of that sample was last in the cavity.

If water was injected but the entire sample measurement failed for other reasons (e.g. the device has not written any output to the data file), I am afraid that then we do not have any means to do the correction. All we can do is to use the uncorrected value (from C in the above example) for approximating the true previous value to correct sample D, and maybe issue a warning for this sample; and then continue normally.

Single injection failure is relatively frequent, whereas I cannot recall if I ever encountered entire sample failure. I would suggest to ask Mikaela (and/or Alexandra) how often they experience this issue and if it is related to total injection failure or to other reasons.

**Comment by twollnik** [comment]
Most often measurements are `NA` because no water was injected at all. Therefore it makes sense to use the last known delta true for the memory correction of the next sample.

**Comment by thomas-muench** [comment]
> Most often measurements are `NA` because no water was injected at all. Therefore it makes sense to use the last known delta true for the memory correction of the next sample.

This decision was implemented in EarthSystemDiagnostics/piccr#29; closing this issue.
